Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    servers = [
        { name: "manager01", ip: "192.168.56.10", memory: 2048, cpus: 2 },
        { name: "worker01", ip: "192.168.56.11", memory: 2048, cpus: 2 },
        { name: "worker02", ip: "192.168.56.12", memory: 2048, cpus: 2 }
    ]

    servers.each do |server|
        config.vm.define server[:name] do |node|
            node.vm.hostname = server[:name]
            node.vm.network "private_network", ip: server[:ip]

            node.vm.provider "virtualbox" do |vb|
              vb.name = server[:name]
              vb.memory = server[:memory]
              vb.cpus = server[:cpus]
          end

          if server[:name] == "manager01"
            node.vm.synced_folder "./services", "/home/vagrant/services"
          end

          node.vm.provision "shell", path: "scripts/install-docker.sh"
        end
    end
end    
